### ISSUE TITLE
LDAC support - 96kHZ 32 bit depth

### ISSUE THREAD

**Issue by candiduslynx** [vipersaudio/viper4android_fx#82]
Have an issue with driver (Processing: no) on my MI MIX 2 with RR + V4A installed either via TWRP or Magisk when codec is set to LDAC. WIth SBC everything works fine.
Especially, it doesn't work with sample rate 96 kHz and 32 bit depth.
On the lesser level, however (44.1 kHz 16 bit) it works.

**Comment by Atemu** [comment]
This is a non issue, for audio reproduction to a human target (which this app is made for) there is absolutely nothing to be gained by going above 16bit 44.1KHz||48KHz. 
For Bluetooth that might even be detrimental to audio quality as more of the very limited Bluetooth bitrate needs to be allocated to transmit imperceivable (and therefore useless) information instead of using it to reduce the losses on the information you can actually perceive.
